In [6]:
import numpy as np

In [2]:
element_ids = [1, 2, 3, 4]
ids = np.array(element_ids)

In [3]:
a = np.tile(ids, (4, 1))
a

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [4]:
b = np.tile(ids[:, np.newaxis], (1, 4))
b

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]])

In [7]:
matrix = np.stack((b, a), axis=2)
matrix

array([[[1, 1],
        [1, 2],
        [1, 3],
        [1, 4]],

       [[2, 1],
        [2, 2],
        [2, 3],
        [2, 4]],

       [[3, 1],
        [3, 2],
        [3, 3],
        [3, 4]],

       [[4, 1],
        [4, 2],
        [4, 3],
        [4, 4]]])

In [9]:
matrix[0]

array([[1, 1],
       [1, 2],
       [1, 3],
       [1, 4]])

In [16]:
colnames = ['name1', 'name2len', 'dx']
rownames = ['a', 'b', 'another']
max_colname = len(max(colnames))
max_rowname = len(max(rownames))

In [18]:
max_colname

8

In [24]:
for cn in [""] + colnames:
    s = "{:" + str(max_colname) + "}"
    print(s.format(cn), end=" | ")
print()
for rn in rownames:
    s = "{:" + str(max_rowname) + "}"
    print(s.format(rn), end=" |\n")

         | name1    | name2len | dx       | 
a |
b |
another |
