In [1]:
import numpy as np

In [10]:
M = np.array([[0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.20833333, 0.10416667, 0.        ],
        [0.        , 0.10416667, 0.20833333, 0.        ],
        [0.        , 0.        , 0.        , 0.        ]],
)

In [20]:
M

array([[0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.20833333, 0.10416667, 0.        ],
       [0.        , 0.10416667, 0.20833333, 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

In [25]:
M[np.any(M != 0.0, axis=0)][:, np.any(M != 0.0, axis=1)]

array([[0.20833333, 0.10416667],
       [0.10416667, 0.20833333]])

In [17]:
M[:, np.any(M != 0.0, axis=0)]

array([[0.        , 0.        ],
       [0.20833333, 0.10416667],
       [0.10416667, 0.20833333],
       [0.        , 0.        ]])

In [44]:
mask = (M != 0.)
mask

array([[False, False, False, False],
       [False,  True,  True, False],
       [False,  True,  True, False],
       [False, False, False, False]])

In [48]:
sec = np.where(np.any(M, axis=1))
sec

(array([1, 2], dtype=int64),)

In [51]:
hbc = np.array([[[1, 0.        , 0.        , 2],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [3, 0.        , 0.        , 4]],

       [[0.        , 0.        , 0.        , 0.        ],
        [0.        , 10, 11, 0.        ],
        [0.        , 12, 13, 0.        ],
        [0.        , 0.        , 0.        , 0.        ]],

       [[0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 50, 60],
        [0.        , 0.        , 70, 90]],

       [[0.20833333, 0.10416667, 0.        , 0.        ],
        [0.10416667, 0.20833333, 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ]]])

In [55]:
mask = (hbc != 0)

In [58]:
hbc[mask].reshape(4, 2, 2)

array([[[ 1.        ,  2.        ],
        [ 3.        ,  4.        ]],

       [[10.        , 11.        ],
        [12.        , 13.        ]],

       [[50.        , 60.        ],
        [70.        , 90.        ]],

       [[ 0.20833333,  0.10416667],
        [ 0.10416667,  0.20833333]]])