In [1]:
import numpy as np

<br><hr>
<h2>Class definitions</h2>

In [228]:
class ArrayCreator:
    def __init__(self) -> None:
        # Construct an array
        a1 = np.arange(1, 5)
        self.arr = a1[3]*a1[:3][:,np.newaxis] + a1
        self.arr = np.vstack((a1, self.arr))
    
    def get_arr(self) -> np.array:
        return self.arr

In [216]:
class DiagonalManager:
    def __init__(self, arg_arr) -> None:
        self.diagonal = arg_arr.get_arr().diagonal()
        self.diagonal_len = len(self.diagonal)
        
        # Set flag to turn off read-only for self.diagonal
        self.diagonal.flags['WRITEABLE'] = True
    
    def get_diagonal(self) -> np.array:
        return self.diagonal
    
    def set_diagonal(self, arg_diagonal: np.array):
        if len(arg_diagonal) == self.diagonal_len:
            self.diagonal[:] = arg_diagonal

<br><hr>
<h2>Program</h2>

In [239]:
# Create object taking advantage of the matrix
M = ArrayCreator()
M.get_arr()

In [230]:
# Create DiagonalManager instance, print out diagonal
DM = DiagonalManager(M)
DM.get_diagonal()

array([ 1,  6, 11, 16])

In [227]:
# Test the method that will change diagonal in original matrix - M
DM.set_diagonal(np.array((11, 22, 33, 44)))

<br><hr>
<h2>The rest</h2>

In [198]:
DM.set_sqr(np.array(((10, 12), (323, 32))))

TypeError: 'ArrayCreator' object does not support item assignment

In [238]:
import sys
print(sys.version)

3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]


In [249]:
for a in reversed(q):
    print(a)

[13 14 15 16]
[ 9 10 11 12]
[5 6 7 8]
[1 2 3 4]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])