In [8]:
import numpy as np

<br><hr>
<h2>Class definitions</h2>

In [9]:
class ArrayCreator:
    def __init__(self) -> None:
        # Construct an array
        a1 = np.arange(1, 5)
        self.arr = a1[3]*a1[:3][:,np.newaxis] + a1
        self.arr = np.vstack((a1, self.arr))
    
    def get_arr(self) -> np.array:
        return self.arr

In [10]:
class DiagonalManager:
    def __init__(self, arg_arr) -> None:
        self.diagonal = arg_arr.get_arr().diagonal()
        self.diagonal_len = len(self.diagonal)
        
        # Set flag to turn off read-only for self.diagonal
        self.diagonal.flags['WRITEABLE'] = True
    
    def get_diagonal(self) -> np.array:
        return self.diagonal
    
    def set_diagonal(self, arg_diagonal: np.array):
        if len(arg_diagonal) == self.diagonal_len:
            self.diagonal[:] = arg_diagonal

<br><hr>
<h2>Program</h2>

In [11]:
# Create object taking advantage of the matrix
M = ArrayCreator()
M.get_arr()

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [12]:
# Create DiagonalManager instance, print out diagonal
DM = DiagonalManager(M)
DM.get_diagonal()

array([ 1,  6, 11, 16])

In [13]:
# Test the method that will change diagonal in original matrix - M
DM.set_diagonal(np.array((11, 22, 33, 44)))

<br><hr>
<h2>The rest</h2>

In [14]:
import sys
print(sys.version)

3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]


In [15]:
q = M.get_arr()

In [16]:
for a in reversed(q):
    print(a)

[13 14 15 44]
[ 9 10 33 12]
[ 5 22  7  8]
[11  2  3  4]


In [17]:
_from, _to = 0, 2

In [18]:
len(q)-_to

2

In [22]:
q

array([[11,  2,  3,  4],
       [ 5, 22,  7,  8],
       [ 9, 10, 33, 12],
       [13, 14, 15, 44]])

In [23]:
q[1:4, 0:2]

array([[ 5, 22],
       [ 9, 10],
       [13, 14]])

In [20]:
q[len(q)-_to:len(q)-_from, _from:_to]

array([[ 9, 10],
       [13, 14]])