In [24]:
import numpy as np
from numpy.polynomial.legendre import leggauss
import itertools as it
import scipy.integrate as integ

In [3]:
# first array: wezly x_n, secont array: wsp A_k (wagi)
L1 = leggauss(2)
L1

(array([-0.57735027,  0.57735027]), array([1., 1.]))

In [4]:
np.column_stack(L1)

array([[-0.57735027,  1.        ],
       [ 0.57735027,  1.        ]])

In [13]:
# Definicje funkcji
f1 = lambda x: 5*x**2 + 3*x + 6
f2 = lambda x, y: 5*x**2*y**2 + 3*x*y + 6

In [14]:
L1 = leggauss(2)
L1zipped = np.column_stack(L1)
# Policzenie całki dla f1
s = 0
for x, w in L1zipped:
    s += f1(x)*w

s

15.333333333333332

In [33]:
L1

(array([-0.77459667,  0.        ,  0.77459667]),
 array([0.55555556, 0.88888889, 0.55555556]))

In [36]:
list(it.combinations(L1[0], 3))

[(-0.7745966692414834, 0.0, 0.7745966692414834)]

In [30]:
L1 = leggauss(3)
L1zipped = np.column_stack(L1)
xs = L1[0]
# Policzenie całki dla f1
s = 0
for j, wy in enumerate(L1[1]):
    for i, wx in enumerate(L1[1]):
        s += f2(xs[i], xs[j]) * wx * wy

s

26.222222222222232

In [37]:
a = 1, 2, 3

In [39]:
list(zip(a, a))

[(1, 1), (2, 2), (3, 3)]

In [42]:
list(it.combinations(a, 2))

[(1, 2), (1, 3), (2, 3)]

In [11]:
L2 = leggauss(3)
L2

(array([-0.77459667,  0.        ,  0.77459667]),
 array([0.55555556, 0.88888889, 0.55555556]))

In [34]:
s = 0
for x, w in zip(*L2):
    s += f1(x)*w
s

15.333333333333336

In [ ]:
for i 