In [10]:
import numpy as np
from numpy.polynomial.legendre import leggauss

In [23]:
# first array: wezly x_n, secont array: wsp A_k (wagi)
L1 = leggauss(2)
L1

(array([-0.57735027,  0.57735027]), array([1., 1.]))

In [24]:
f1 = lambda x: 5*x**2 + 3*x + 6

In [20]:
1/np.sqrt(3)

0.5773502691896258

In [28]:
s = 0
for x, w in zip(*L1):
    s += f1(x)*w

s

15.333333333333332

In [29]:
f2 = lambda x, y: 5*x**2*y**2 + 3*x*y + 6

In [32]:
L2 = leggauss(3)
L2

(array([-0.77459667,  0.        ,  0.77459667]),
 array([0.55555556, 0.88888889, 0.55555556]))

In [34]:
s = 0
for x, w in zip(*L2):
    s += f1(x)*w
s

15.333333333333336

In [ ]:
for i 