In [1]:
import numpy as np
import itertools as it
from numpy.polynomial.legendre import leggauss

In [30]:
f = lambda N: np.arange(1, N+1) + np.arange(0, N*N, N)[:, np.newaxis] 
x = f(3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
d = {'a': 3}

In [32]:
np.array([1])[np.newaxis]

array([[1]])

In [33]:
np.arange(1, 4, 2)

array([1, 3])

In [34]:
c1 = it.cycle('ab')

In [35]:
next(c1)

'a'

In [36]:
class ItemManager:
    def __init__(self, arg_arr: list[list]):
        self.arr: list[list] = arg_arr
    
    def print_arr(self):
        for i in self.arr:
            for j in i:
                print(j, end=' ')
            print()
            
    def __getitem__(self, pos: tuple):
        i, j = pos
        return self.arr[i][j]
    
    

In [37]:
i1 = ItemManager([[1, 2], [3, 4], [5, 6]])

In [38]:
i1[1, 1]

4

In [39]:
import numpy as np

In [40]:
def convert_id_to_coord(arg_id: int, arg_shape: tuple):
    x = (arg_id - 1) // (arg_shape[0])
    y = (arg_id - 1) % arg_shape[0]
    y = ((arg_shape[0] - 1) - y)

    return x, y

In [41]:
convert_id_to_coord(4, (2, 4))

(1, 0)

In [42]:
Le = leggaus(2)

NameError: name 'leggaus' is not defined

In [ ]:
L = leggauss(2)
_L = np.vstack((L[0][::-1], L[0][::-1]))[np.newaxis]
_L

array([[[ 0.57735027, -0.57735027],
        [ 0.57735027, -0.57735027]]])

In [ ]:
L[0][::-1]

array([ 0.57735027, -0.57735027])

In [ ]:
L
_L = np.array([L[0][0], L[0][0], L[0][1], L[0][1]])
_L

array([-0.57735027, -0.57735027,  0.57735027,  0.57735027])

In [ ]:
np.hstack((L[0], L[0][::-1])).T

array([-0.57735027,  0.57735027,  0.57735027, -0.57735027])

In [ ]:
dd = np.array([10, 10, 10, 10]) * np.array([2, 3, 4, 5])
dd

array([20, 30, 40, 50])

In [ ]:
np.sum(dd)

140

In [ ]:
np.eye([1, 2, 3])

TypeError: 'list' object cannot be interpreted as an integer

In [ ]:
arr = np.array([1, 2, 3, 4])

In [68]:
test = [[i for i in range(g*3, g*3+3)] for g in range(3)]

In [69]:
test

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

In [ ]:
_ = [print(j) for i in test for j in i]

0
1
2
3
4
5
6
7
8


In [ ]:
x = np.array([[1, 2], [3, 4]])
v = np.array([3, 4])

In [ ]:
fillme = np.empty((4, 4, 4), dtype=int)

In [ ]:
vs = np.arange(0, 4*4, 4)[:, np.newaxis] + np.arange(0, 4)

In [ ]:
fillme[0] = vs

In [46]:
d = np.arange(0, 4*4, 4)[:, np.newaxis] + np.arange(0, 4)

In [65]:
d

array([[ 5,  1,  2,  5],
       [ 4,  6,  6,  7],
       [ 8,  5,  5, 11],
       [ 6, 13, 14,  6]])

In [60]:
_id = d[:, ::-1].diagonal()
_id

array([ 3,  6,  9, 12])

In [2]:
np.fill_diagonal(d[:, ::-1], [5, 6, 5, 6])

NameError: name 'd' is not defined

In [47]:
a = np.array([[-31.54700538,  31.54700538,   8.45299462,  -8.45299462],
       [-31.54700538,  31.54700538,   8.45299462,  -8.45299462],
       [ -8.45299462,   8.45299462,  31.54700538, -31.54700538],
       [ -8.45299462,   8.45299462,  31.54700538, -31.54700538]])
b = a

In [59]:
a[-1, :]

array([ -8.45299462,   8.45299462,  31.54700538, -31.54700538])

In [54]:
c[0] = 1000
c, a

(array([1000.        ,   31.54700538,    8.45299462,   -8.45299462]),
 array([[-31.54700538,  31.54700538,   8.45299462,  -8.45299462],
        [-31.54700538,  31.54700538,   8.45299462,  -8.45299462],
        [ -8.45299462,   8.45299462,  31.54700538, -31.54700538],
        [ -8.45299462,   8.45299462,  31.54700538, -31.54700538]]))

In [32]:
b[0][:, np.newaxis] * a[0]

array([[ 995.21354845, -995.21354845, -266.66666675,  266.66666675],
       [-995.21354845,  995.21354845,  266.66666675, -266.66666675],
       [-266.66666675,  266.66666675,   71.45311805,  -71.45311805],
       [ 266.66666675, -266.66666675,  -71.45311805,   71.45311805]])

In [31]:
r = it.repeat(False)
d = dict(it.zip_longest(['a', 'b', 'c'], (True, False, True), fillvalue=False))

In [43]:
c[0] = 5

In [35]:
d
len([i for i in d.values() if i])

2

In [60]:
i = True

In [66]:
i &= True
i

False

In [71]:
L = leggauss(2)
L

(array([-0.57735027,  0.57735027]), array([1., 1.]))

In [72]:
np.zeros((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [82]:
L[0]

array([ 0.57735027, -0.57735027])

In [10]:
class MyCls:
    def __init__(self) -> None:
        self.one = np.zeros((4, 4))
        self.two = np.zeros((4, 4))
        self.arr = [self.one, self.two]


In [ ]:
o1 = MyCls()
o1.two

In [12]:
s = '''[[-0.39433757  0.39433757  0.10566243 -0.10566243]
 [-0.10566243  0.10566243  0.39433757 -0.39433757]
 [-0.10566243  0.10566243  0.39433757 -0.39433757]
 [-0.39433757  0.39433757  0.10566243 -0.10566243]]'''

s2 = '''[[-0.39433757  0.39433757  0.10566243 -0.10566243]
 [-0.10566243  0.10566243  0.39433757 -0.39433757]
 [-0.10566243  0.10566243  0.39433757 -0.39433757]
 [-0.39433757  0.39433757  0.10566243 -0.10566243]]'''

In [13]:
s == s2

True

In [19]:
x = np.array([])

In [24]:
x.size

0

In [23]:
'a' if x.size else 'b'

'b'

In [96]:
n_nodes = 2, 4
_array = np.zeros(n_nodes)

In [109]:
arg_nodes = np.array([[3, 4, 23, 33], [50, 20, 1, 2]])
for col in range(n_nodes[1]):
    for row in reversed(range(n_nodes[0])):
        _array[row, col] = arg_nodes[row, col]

In [115]:
arg_nodes = np.array([[3, 4, 23, 33], [50, 20, 1, 2]])
for row in range(n_nodes[0]):
    for col in range(n_nodes[1]):
        _array[row, col] = arg_nodes[row, col]

In [116]:
_array

array([[ 3.,  4., 23., 33.],
       [50., 20.,  1.,  2.]])

In [108]:
_array[::-1][1, 2]

23.0

In [80]:
[i for i in reversed(range(3))]

[2, 1, 0]

In [45]:
print(_array[:, 0])
print(_array[:, -1])
print(_array[0, :])
print(_array[-1, :])

[ 3. 50.]
[33.  2.]
[ 3.  4. 23. 33.]
[50. 20.  1.  2.]


In [40]:
_array

array([[ 3.,  4., 23., 33.],
       [50., 20.,  1.,  2.]])

In [121]:
is_a = 3
is_b = 5
ab = [is_a, is_b]

In [124]:
is_a = 6
ab

[3, 5]

In [18]:
edge = {
    "is_left": False,
    "is_right": False,
    "is_top": False,
    "is_bottom": False
}

In [19]:
any(edge.values())

True

In [11]:
data = {"is_left": True}
data2 = False, True, True, False
def setter(*args, **kwargs):
    if kwargs:
        for k, v in kwargs.items():
            edge[k] = v
    
    elif args:
        for varg, k in zip(args, edge.keys()):
            edge[k] = varg
    
    

In [12]:
setter(**data)

NameError: name 'edge' is not defined

In [ ]:
setter(*data2)

In [ ]:
setter(True, True)

In [ ]:
setter(is_left=True)

False True


In [ ]:
edge

{'is_left': True, 'is_right': True, 'is_top': False, 'is_bottom': False}

In [ ]:
d = [0, 0, 0, 0]
def foo(pos=2):
    d[pos] = 1

In [ ]:
[True if i == 2 else False for i in range(4)]

[False, False, True, False]

In [20]:
s = ""

In [24]:
s

'ab'

In [23]:
s += 'b'