In [2]:
import numpy as np
import itertools as it
from numpy.polynomial.legendre import leggauss

In [42]:
f = lambda N: np.arange(1, N+1) + np.arange(0, N*N, N)[:, np.newaxis] 
x = f(3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
d = {'a': 3}

In [53]:
np.array([1])[np.newaxis]

array([[1]])

In [19]:
np.arange(1, 4, 2)

array([1, 3])

In [30]:
c1 = it.cycle('ab')

In [41]:
next(c1)

'a'

In [13]:
class ItemManager:
    def __init__(self, arg_arr: list[list]):
        self.arr: list[list] = arg_arr
    
    def print_arr(self):
        for i in self.arr:
            for j in i:
                print(j, end=' ')
            print()
            
    def __getitem__(self, pos: tuple):
        i, j = pos
        return self.arr[i][j]
    
    

In [14]:
i1 = ItemManager([[1, 2], [3, 4], [5, 6]])

In [15]:
i1[1, 1]

4

In [1]:
import numpy as np

In [7]:
def convert_id_to_coord(arg_id: int, arg_shape: tuple):
    x = (arg_id - 1) // (arg_shape[0])
    y = (arg_id - 1) % arg_shape[0]
    y = ((arg_shape[0] - 1) - y)

    return x, y

In [13]:
convert_id_to_coord(4, (2, 4))

(1, 0)

In [58]:
Le = leggaus(2)

NameError: name 'leggaus' is not defined

In [16]:
L = leggauss(2)
_L = np.vstack((L[0][::-1], L[0][::-1]))[np.newaxis]
_L

array([[[ 0.57735027, -0.57735027],
        [ 0.57735027, -0.57735027]]])

In [5]:
L[0][::-1]

array([ 0.57735027, -0.57735027])

In [18]:
L
_L = np.array([L[0, 0], L[0, 0], L[0, 1], L[0, 1]])

TypeError: tuple indices must be integers or slices, not tuple

In [31]:
np.hstack((L[0], L[0][::-1]))

array([-0.57735027,  0.57735027,  0.57735027, -0.57735027])