In [106]:
import numpy as np
import timeit

In [107]:
a = np.array([1, 2, 3, 4])
b = np.array([0, 100, 5, 1])
j = np.array([[80, 0], [0, 80]])

In [108]:
j

array([[80,  0],
       [ 0, 80]])

In [109]:
v = np.stack((a, b), axis=1)[:, :, np.newaxis]
v

array([[[  1],
        [  0]],

       [[  2],
        [100]],

       [[  3],
        [  5]],

       [[  4],
        [  1]]])

In [110]:
j @ v

array([[[  80],
        [   0]],

       [[ 160],
        [8000]],

       [[ 240],
        [ 400]],

       [[ 320],
        [  80]]])

In [111]:
%%time
for _ in range(int(1e5)):
    np.stack((a, b), axis=1)[:, :, np.newaxis]

Wall time: 749 ms


In [112]:
%%time
for _ in range(int(1e5)):
    np.stack((a, b), axis=1).reshape(4, 2, 1)

Wall time: 760 ms


In [113]:
v

array([[[  1],
        [  0]],

       [[  2],
        [100]],

       [[  3],
        [  5]],

       [[  4],
        [  1]]])

In [114]:
np.squeeze(v, axis=2)

array([[  1,   0],
       [  2, 100],
       [  3,   5],
       [  4,   1]])

In [115]:
transpose(v)

NameError: name 'transpose' is not defined

In [ ]:
x = np.array([[[-31.54700538,  31.54700538,   8.45299462,  -8.45299462],
        [-31.54700538,  31.54700538,   8.45299462,  -8.45299462],
        [ -8.45299462,   8.45299462,  31.54700538, -31.54700538],
        [ -8.45299462,   8.45299462,  31.54700538, -31.54700538]],

       [[-31.54700538,  -8.45299462,   8.45299462,  31.54700538],
        [ -8.45299462, -31.54700538,  31.54700538,   8.45299462],
        [ -8.45299462, -31.54700538,  31.54700538,   8.45299462],
        [-31.54700538,  -8.45299462,   8.45299462,  31.54700538]]])

In [ ]:
x

array([[[-31.54700538,  31.54700538,   8.45299462,  -8.45299462],
        [-31.54700538,  31.54700538,   8.45299462,  -8.45299462],
        [ -8.45299462,   8.45299462,  31.54700538, -31.54700538],
        [ -8.45299462,   8.45299462,  31.54700538, -31.54700538]],

       [[-31.54700538,  -8.45299462,   8.45299462,  31.54700538],
        [ -8.45299462, -31.54700538,  31.54700538,   8.45299462],
        [ -8.45299462, -31.54700538,  31.54700538,   8.45299462],
        [-31.54700538,  -8.45299462,   8.45299462,  31.54700538]]])

In [ ]:
x[0, 0][:, np.newaxis] * x[0, 0] 

array([[ 995.21354845, -995.21354845, -266.66666675,  266.66666675],
       [-995.21354845,  995.21354845,  266.66666675, -266.66666675],
       [-266.66666675,  266.66666675,   71.45311805,  -71.45311805],
       [ 266.66666675, -266.66666675,  -71.45311805,   71.45311805]])

In [ ]:
r = np.stack((x[0], x[1]), axis=1)
r

array([[[-31.54700538,  31.54700538,   8.45299462,  -8.45299462],
        [-31.54700538,  -8.45299462,   8.45299462,  31.54700538]],

       [[-31.54700538,  31.54700538,   8.45299462,  -8.45299462],
        [ -8.45299462, -31.54700538,  31.54700538,   8.45299462]],

       [[ -8.45299462,   8.45299462,  31.54700538, -31.54700538],
        [ -8.45299462, -31.54700538,  31.54700538,   8.45299462]],

       [[ -8.45299462,   8.45299462,  31.54700538, -31.54700538],
        [-31.54700538,  -8.45299462,   8.45299462,  31.54700538]]])

In [147]:
r[:, 0][:, :, np.newaxis] * r[:, 0][:, np.newaxis]

array([[[ 995.21354845, -995.21354845, -266.66666675,  266.66666675],
        [-995.21354845,  995.21354845,  266.66666675, -266.66666675],
        [-266.66666675,  266.66666675,   71.45311805,  -71.45311805],
        [ 266.66666675, -266.66666675,  -71.45311805,   71.45311805]],

       [[ 995.21354845, -995.21354845, -266.66666675,  266.66666675],
        [-995.21354845,  995.21354845,  266.66666675, -266.66666675],
        [-266.66666675,  266.66666675,   71.45311805,  -71.45311805],
        [ 266.66666675, -266.66666675,  -71.45311805,   71.45311805]],

       [[  71.45311805,  -71.45311805, -266.66666675,  266.66666675],
        [ -71.45311805,   71.45311805,  266.66666675, -266.66666675],
        [-266.66666675,  266.66666675,  995.21354845, -995.21354845],
        [ 266.66666675, -266.66666675, -995.21354845,  995.21354845]],

       [[  71.45311805,  -71.45311805, -266.66666675,  266.66666675],
        [ -71.45311805,   71.45311805,  266.66666675, -266.66666675],
        [-266.

In [146]:
r[:, 1][:, :, np.newaxis] * r[:, 1][:, np.newaxis]

array([[[ 995.21354845,  266.66666675, -266.66666675, -995.21354845],
        [ 266.66666675,   71.45311805,  -71.45311805, -266.66666675],
        [-266.66666675,  -71.45311805,   71.45311805,  266.66666675],
        [-995.21354845, -266.66666675,  266.66666675,  995.21354845]],

       [[  71.45311805,  266.66666675, -266.66666675,  -71.45311805],
        [ 266.66666675,  995.21354845, -995.21354845, -266.66666675],
        [-266.66666675, -995.21354845,  995.21354845,  266.66666675],
        [ -71.45311805, -266.66666675,  266.66666675,   71.45311805]],

       [[  71.45311805,  266.66666675, -266.66666675,  -71.45311805],
        [ 266.66666675,  995.21354845, -995.21354845, -266.66666675],
        [-266.66666675, -995.21354845,  995.21354845,  266.66666675],
        [ -71.45311805, -266.66666675,  266.66666675,   71.45311805]],

       [[ 995.21354845,  266.66666675, -266.66666675, -995.21354845],
        [ 266.66666675,   71.45311805,  -71.45311805, -266.66666675],
        [-266.

In [145]:
r[:, 0][:, np.newaxis]

array([[[-31.54700538,  31.54700538,   8.45299462,  -8.45299462]],

       [[-31.54700538,  31.54700538,   8.45299462,  -8.45299462]],

       [[ -8.45299462,   8.45299462,  31.54700538, -31.54700538]],

       [[ -8.45299462,   8.45299462,  31.54700538, -31.54700538]]])

In [139]:
r[:, 0][:, :, np.newaxis]

array([[[-31.54700538],
        [ 31.54700538],
        [  8.45299462],
        [ -8.45299462]],

       [[-31.54700538],
        [ 31.54700538],
        [  8.45299462],
        [ -8.45299462]],

       [[ -8.45299462],
        [  8.45299462],
        [ 31.54700538],
        [-31.54700538]],

       [[ -8.45299462],
        [  8.45299462],
        [ 31.54700538],
        [-31.54700538]]])

In [ ]:
np.multiply()